# Generated by Django 5.2 on 2025-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='trending',
            field=models.BooleanField(default=0),
        ),
    ]
